# Generated by Django 4.2.7 on 2024-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.IntegerField()),
                ("district_id", models.IntegerField()),
                ("longitude", models.FloatField()),
                ("city_type", models.CharField(max_length=550)),
                ("status", models.CharField(max_length=550)),
                ("region", models.CharField(max_length=550)),
                ("city_id", models.IntegerField()),
                ("district", models.CharField(max_length=550)),
                ("city", models.CharField(max_length=550)),
            ],
            options={
                "verbose_name": "Населений пункт",
                "verbose_name_plural": "Населені пункти",
            },
        ),
    ]
