# Generated by Django 4.2.7 on 2024-03-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukr_poshta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="own_of",
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
