# Generated by Django 4.2.7 on 2024-03-25 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukr_poshta", "0002_city_own_of"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="own_of",
        ),
    ]
