# Generated by Django 4.2.7 on 2024-03-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ukr_poshta", "0003_remove_city_own_of"),
    ]

    operations = [
        migrations.CreateModel(
            name="UkrOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_office", models.CharField(max_length=550)),
                ("post_code", models.IntegerField()),
                ("longitude", models.FloatField()),
                ("street", models.CharField(max_length=550)),
                ("post_office_id", models.IntegerField()),
                ("status", models.CharField(max_length=550)),
                ("type", models.CharField(max_length=550)),
                (
                    "related_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_city",
                        to="ukr_poshta.city",
                        verbose_name="Населений пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Офіс",
                "verbose_name_plural": "Офіси",
            },
        ),
    ]
