# Generated by Django 4.2.7 on 2026-07-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delivery_city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Місто доставки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_settlement_ref',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Ref міста НП'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_warehouse',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Відділення НП'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_warehouse_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ID відділення НП'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_warehouse_ref',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Ref відділення НП'),
        ),
    ]
