FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    uwsgi \
    uwsgi-plugin-python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p static_root media config logs && \
    chown -R www-data:www-data /app

RUN python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["uwsgi", "--ini", "/app/config/mrcarpet.ini"]
