# Generated by Django 4.2.7 on 2026-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiqPaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255, verbose_name='Public key')),
                ('private_key', models.CharField(max_length=255, verbose_name='Private key')),
            ],
            options={
                'verbose_name': 'Налаштування LiqPay',
                'verbose_name_plural': 'Налаштування LiqPay',
            },
        ),
    ]
