# Generated by Django 4.2.7 on 2025-09-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_poshta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API ключ')),
            ],
            options={
                'verbose_name': 'Налаштування Nova Poshta',
                'verbose_name_plural': 'Налаштування Nova Poshta',
            },
        ),
    ]
