"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rzqw(#2172p@li9y6n#)sjq)21tt+fdxacur1_!+(0%l_&v)9+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# SEO / indexing. Local/dev default False; prod sets SEO_INDEXING_ENABLED=true
# via docker-compose.prod.yml → robots Allow + index,follow on public pages.
# Private pages (cart/checkout/…) always force noindex in templates.
SEO_INDEXING_ENABLED = config("SEO_INDEXING_ENABLED", default=False, cast=bool)

# Analytics / measurement (Phase 9). Empty = scripts not injected.
# Example: GA4_MEASUREMENT_ID=G-XXXXXXXXXX
# Prefer GTM_CONTAINER_ID=GTM-XXXXXXX if you manage tags in GTM (then skip raw GA4 id).
GA4_MEASUREMENT_ID = config("GA4_MEASUREMENT_ID", default="")
GTM_CONTAINER_ID = config("GTM_CONTAINER_ID", default="")
# Measurement Protocol API secret (server-only). Create in GA4 → Data stream → MP secrets.
GA4_API_SECRET = config("GA4_API_SECRET", default="")
# Data API (Telegram analytics reports). Property ID = digits only.
GA4_PROPERTY_ID = config("GA4_PROPERTY_ID", default="")
# Full service-account JSON as a single env string (preferred on prod).
GA4_SERVICE_ACCOUNT_JSON = config("GA4_SERVICE_ACCOUNT_JSON", default="")
# Optional path fallback (local ops/ga4/service-account.json).
GOOGLE_APPLICATION_CREDENTIALS = config("GOOGLE_APPLICATION_CREDENTIALS", default="")
GOOGLE_SITE_VERIFICATION = config("GOOGLE_SITE_VERIFICATION", default="")
# Bump on each frontend deploy so browsers bypass nginx immutable 30d JS/CSS cache.
STATIC_ASSET_VERSION = config("STATIC_ASSET_VERSION", default="20260719h")

# Behind nginx TLS termination (see config/mrcarpet.docker X-Forwarded-Proto).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# CSRF налаштування для webhook від LiqPay через ngrok
# Додайте ваш ngrok URL сюди
CSRF_TRUSTED_ORIGINS = [
    "https://21f997f18ee0.ngrok-free.app",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://178.128.196.94",
    "https://mrcarpet24.com",
    "https://www.mrcarpet24.com",
    "http://mrcarpet24.com",
    "http://www.mrcarpet24.com",
]

# Для додавання нових ngrok URL через змінну оточення (опціонально):
# Додайте в .env: CSRF_TRUSTED_ORIGINS=https://your-ngrok-url.ngrok-free.app,http://localhost:8000
# І розкоментуйте наступний рядок:
# CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',') if config('CSRF_TRUSTED_ORIGINS', default='') else CSRF_TRUSTED_ORIGINS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'project',
    'blog',
    'cart',
    's_content',
    's_utils',
    'catalog',
    'order.apps.OrderConfig',
    'users',
    'nova_poshta',
    'ukr_poshta',
    'payment',
    'rest_framework',
    'django_filters',
    'drf_yasg',
    'colorfield',
    # "django_celery_beat",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalog.context_processors.context',
                'cart.context_processors.context',
                'project.context_processors.seo_jsonld',
                'project.context_processors.shop_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

_db_engine = config('DB_ENGINE', 'django.db.backends.sqlite3')
DATABASES = {
    'default': {
        'ENGINE': _db_engine,
        'NAME': config('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': config('DB_USER', None),
        'PASSWORD': config('DB_PASSWORD', None),
        'HOST': config('DB_HOST', None),
        'PORT': config('DB_PORT', None),
    }
}

# SQLite + кілька gunicorn workers = "database is locked". Timeout + WAL пом’якшують.
if _db_engine.endswith('sqlite3'):
    DATABASES['default']['OPTIONS'] = {
        'timeout': 30,
    }

    from django.db.backends.signals import connection_created

    def _sqlite_optimize(sender, connection, **kwargs):
        if connection.vendor != 'sqlite':
            return
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA busy_timeout=30000;')
        cursor.execute('PRAGMA synchronous=NORMAL;')

    connection_created.connect(_sqlite_optimize)

# Ліміт очікування SMTP (Gmail тощо), щоб сокет не висів хвилинами
EMAIL_TIMEOUT = 12


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "media/"
STATIC_ROOT = "static_root/"
MEDIA_ROOT = "media/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'ORDERING_PARAM': 'sort',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
}

LIQPAY_PUBLIC_KEY = config("LIQPAY_PUBLIC_KEY", None)
LIQPAY_PRIVATE_KEY = config("LIQPAY_PRIVATE_KEY", None)

REPLICATE_API_TOKEN = config("REPLICATE_API_TOKEN", default=None)

# Absolute site URL for Telegram product links etc.
SITE_URL = config("SITE_URL", default="https://mrcarpet24.com").rstrip("/")
# Real mailbox for replies / footer (From for sending can stay orders@ via Brevo)
SUPPORT_EMAIL = config("SUPPORT_EMAIL", default="mr.carpet.shop@gmail.com")

# CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://localhost:6379/0")
# CELERY_RESULT_BACKEND = os.environ.get("CELERY_BACKEND", "redis://localhost:6379/0")

# CELERY_BEAT_SCHEDULE = { # scheduler configuration
#     'Task_one_schedule' : {  # whatever the name you want
#         'task': 'order.tasks.remove_orders', # name of task with path
#         'schedule': crontab(hour=0, minute=0), # crontab() runs the tasks every minute
#     },
# }


# SMTP settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST = "smtp.gmail.com"
SERVER_EMAIL = config('EMAIL_HOST_USER')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "catalog.replicate": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "catalog.seo_generate": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "nova_poshta.api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "nova_poshta.sync": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}