# Generated by Django 4.2 on 2023-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keys', models.TextField(blank=True, null=True, verbose_name='Meta Keys')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Created automatically', max_length=512, null=True, verbose_name='Unique label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='articles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
