# Generated by Django 4.2.7 on 2025-09-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Стаття блогу', 'verbose_name_plural': 'Статті блогу'},
        ),
    ]
