# Generated by Django 4.2.7 on 2026-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Короткий опис для сніпета (~150–160 символів). Пишіть як відповідь на інтент покупця, не keyword soup. Якщо порожньо — fallback з опису / бренду.', null=True, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keys',
            field=models.TextField(blank=True, help_text='Опційно. Google майже ігнорує; можна залишити порожнім.', null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.TextField(blank=True, help_text='Title у вкладці браузера / сніпеті. Якщо порожньо — використовується назва (title).', null=True, verbose_name='SEO Title'),
        ),
    ]
