# Generated by Django 6.0.7 on 2026-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_seo_meta_phase1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published_at', '-created'), 'verbose_name': 'Стаття блогу', 'verbose_name_plural': 'Статті блогу'},
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Момент першої публікації. Дата в розмітці береться звідси.', null=True, verbose_name='Опубліковано'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано')], db_index=True, default='draft', max_length=16, verbose_name='Статус'),
        ),
    ]
