# Generated by Django 6.0.7 on 2026-07-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_article_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема')),
                ('brief', models.TextField(blank=True, default='', help_text='Кут подачі для генератора: що саме має бути в статті.', verbose_name='Що розкрити')),
                ('target_path', models.CharField(blank=True, default='', help_text='Шлях категорії або сторінки, на яку стаття має посилатись, напр. /catalog/categorie/v-ditiachu/. Це і є сенс статті.', max_length=200, verbose_name='Куди вести')),
                ('rank', models.PositiveIntegerField(db_index=True, default=1000, help_text='Менше = раніше. Найсильніші теми йдуть першими.', verbose_name='Черга')),
                ('status', models.CharField(choices=[('pending', 'У черзі'), ('used', 'Використана'), ('skipped', 'Пропущена')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='blog.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Тема для блогу',
                'verbose_name_plural': 'Теми для блогу',
                'ordering': ('rank', 'pk'),
                'indexes': [models.Index(fields=['status', 'rank'], name='blog_articl_status_9f4226_idx')],
            },
        ),
    ]
