# Generated by Django 4.2.7 on 2024-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated"
                    ),
                ),
                ("name", models.CharField(max_length=115, verbose_name="Ім'я")),
                ("email", models.EmailField(max_length=254, verbose_name="Пошта")),
                ("text", models.TextField(verbose_name="Коментар")),
            ],
            options={
                "verbose_name": "Контактна форма",
                "verbose_name_plural": "Контактні форми",
            },
        ),
    ]
