# Generated by Django 4.2.7 on 2025-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('host', models.CharField(max_length=255, verbose_name='Хост')),
                ('server_email', models.EmailField(max_length=254, verbose_name='Email сервера')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Налаштування SMTP',
                'verbose_name_plural': 'Налаштування SMTP',
            },
        ),
    ]
