# Generated by Django 4.2.7 on 2025-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_smtpsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='Використовувати SSL'),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Використовувати TLS'),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логін'),
        ),
    ]
