# Generated by Django 4.2.7 on 2025-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_smtpsettings_use_ssl_smtpsettings_use_tls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Оброблено'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
    ]
