# Generated by Django 4.2.7 on 2026-07-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_seo_meta_phase1'),
        ('project', '0005_contactrequest_is_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=115, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('product_title', models.CharField(blank=True, default='', max_length=512, verbose_name='Назва товару')),
                ('size_label', models.CharField(blank=True, default='', max_length=128, verbose_name='Розмір')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_inquiries', to='catalog.product', verbose_name='Товар')),
                ('product_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_inquiries', to='catalog.productattribute', verbose_name='Варіація / розмір')),
            ],
            options={
                'verbose_name': 'Запит наявності',
                'verbose_name_plural': 'Запити наявності',
                'ordering': ('-created',),
            },
        ),
    ]
