# Generated by Django 4.2.7 on 2026-07-18 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_subscription_newsletter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема листа')),
                ('preheader', models.CharField(blank=True, default='', help_text='Короткий текст у inbox поруч із темою.', max_length=255, verbose_name='Preheader')),
                ('brief', models.TextField(blank=True, default='', help_text='Тези акції, CTA URL, тон. Для кнопки «Згенерувати HTML».', verbose_name='Бриф для AI')),
                ('body_html', models.TextField(blank=True, default='', help_text='Лише внутрішній контент; shell — emails/base.html.', verbose_name='HTML тіла (inner)')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('generating', 'Генерація HTML'), ('ready', 'Готово до відправки'), ('sending', 'Відправляється'), ('sent', 'Надіслано'), ('failed', 'Помилка')], db_index=True, default='draft', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_total', models.PositiveIntegerField(default=0)),
                ('recipients_sent', models.PositiveIntegerField(default=0)),
                ('recipients_failed', models.PositiveIntegerField(default=0)),
                ('ai_model', models.CharField(blank=True, default='', max_length=255)),
                ('ai_prompt_snapshot', models.TextField(blank=True, default='')),
                ('test_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Розсилка (кампанія)',
                'verbose_name_plural': 'Розсилки (кампанії)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Надіслано'), ('failed', 'Помилка'), ('skipped', 'Пропущено')], db_index=True, default='sent', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Доставка розсилки',
                'verbose_name_plural': 'Доставки розсилок',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='telegramchatmessage',
            new_name='project_tel_chat_id_5c5228_idx',
            old_name='project_tel_chat_id_7a2e1f_idx',
        ),
        migrations.AddField(
            model_name='newsletterdelivery',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='project.newslettercampaign'),
        ),
        migrations.AddField(
            model_name='newsletterdelivery',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='project.subscription'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterUniqueTogether(
            name='newsletterdelivery',
            unique_together={('campaign', 'subscription')},
        ),
    ]
