# Generated by Django 6.0.7 on 2026-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_newslettercampaign_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=1499, help_text='Сума товарів (після промокоду), від якої доставка за наш рахунок.', verbose_name='Поріг безкоштовної доставки (грн)'),
        ),
    ]
