# Generated by Django 6.0.7 on 2026-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_shopsettings_free_shipping_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='listen_thread_ids',
            field=models.CharField(blank=True, default='', help_text='Через кому, напр. 1040,915. Бот відповідатиме і тут, і в основному топіку. Порожньо = тільки основний. Це НЕ адреса надсилання звітів — вона лишається в полі вище.', max_length=128, verbose_name='Ще топіки, де бот відповідає'),
        ),
    ]
