# Generated by Django 4.2 on 2023-04-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Улюблені',
                'verbose_name_plural': 'Улюблені',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keys', models.TextField(blank=True, null=True, verbose_name='Meta Keys')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Created automatically', max_length=512, null=True, verbose_name='Unique label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='products', verbose_name='Зображення')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Кількість')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Created automatically', max_length=512, null=True, verbose_name='Unique label')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='categories', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Created automatically', max_length=512, null=True, verbose_name='Unique label')),
            ],
            options={
                'verbose_name': 'Розмір',
                'verbose_name_plural': 'Розміри',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=128, null=True, verbose_name='Висота ворсу')),
                ('main', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ворсова основа')),
                ('style', models.CharField(blank=True, max_length=128, null=True, verbose_name='Стилістика')),
                ('components', models.CharField(blank=True, max_length=128, null=True, verbose_name='Склад')),
                ('form', models.CharField(blank=True, max_length=128, null=True, verbose_name='Форма')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Специфікація',
                'verbose_name_plural': 'Специфікації',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.productcategory', verbose_name='Категорії'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='catalog.productsize', verbose_name='Розміри'),
        ),
        migrations.CreateModel(
            name='FavouriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.favourite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='favourite',
            name='product',
            field=models.ManyToManyField(related_name='fav_products', through='catalog.FavouriteProducts', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
    ]
