# Generated by Django 4.2 on 2023-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='something',
            field=models.CharField(default=1, max_length=12),
        ),
    ]
