# Generated by Django 4.2 on 2023-04-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_favourite_something'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteproducts',
            options={'ordering': ['-order']},
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='something',
        ),
    ]
