# Generated by Django 4.2 on 2023-05-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productspecification_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ціна'),
        ),
    ]
