# Generated by Django 4.2 on 2023-05-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productsizeprice_size_sizeprice_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Ціна')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attr', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Варіація',
                'verbose_name_plural': 'Варіації',
            },
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductSizePrice',
        ),
        migrations.DeleteModel(
            name='SizePrice',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attr', to='catalog.size', verbose_name='Розмір'),
        ),
    ]
