# Generated by Django 4.2 on 2023-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteproducts',
            options={'ordering': ['-order'], 'verbose_name': 'Улюблений товар', 'verbose_name_plural': 'Улюблені товари'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='discount',
            field=models.IntegerField(blank=True, help_text='Знижка у відсотках', null=True, verbose_name='Знижка'),
        ),
    ]
