# Generated by Django 4.2 on 2023-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_favouriteproducts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteproducts',
            options={'verbose_name': 'Улюблений товар', 'verbose_name_plural': 'Улюблені товари'},
        ),
        migrations.AddField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
