# Generated by Django 4.2 on 2023-05-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_favouriteproducts_options_product_has_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='fav_products', through='catalog.FavouriteProducts', to='catalog.product', verbose_name='Товар'),
        ),
    ]
