# Generated by Django 4.2.7 on 2024-01-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_alter_favourite_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="productattribute",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Кількість"),
            preserve_default=False,
        ),
    ]
