# Generated by Django 4.2.7 on 2024-01-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_products', to='catalog.product', verbose_name='Схожий товар')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='catalog.product', verbose_name='Відповідний товар')),
            ],
        ),
    ]
