# Generated by Django 4.2.7 on 2024-01-22 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_relatedproducts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RelatedProducts",
            new_name="RelatedProduct",
        ),
    ]
