# Generated by Django 4.2.7 on 2024-02-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_rename_relatedproducts_relatedproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated"
                    ),
                ),
                ("date_end", models.DateTimeField(verbose_name="Кінець розпродажу")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="catalog.product",
                        verbose_name="Товар на акції",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар на акції",
                "verbose_name_plural": "Товари на акції",
            },
        ),
    ]
