# Generated by Django 4.2.7 on 2024-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_productsale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsale",
            name="product",
        ),
        migrations.AddField(
            model_name="productsale",
            name="products",
            field=models.ManyToManyField(
                to="catalog.product", verbose_name="Товари на акції"
            ),
        ),
    ]
