# Generated by Django 4.2.7 on 2024-02-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_remove_productsale_product_productsale_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsale",
            options={"verbose_name": "Акція", "verbose_name_plural": "Акції"},
        ),
        migrations.AddField(
            model_name="productattribute",
            name="is_new",
            field=models.BooleanField(default=True, verbose_name="Новинка"),
        ),
    ]
