# Generated by Django 4.2.7 on 2024-02-08 18:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_alter_productsale_options_productattribute_is_new"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        help_text="Created automatically",
                        max_length=512,
                        null=True,
                        verbose_name="Unique label",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        unique=True,
                        verbose_name="Колір",
                    ),
                ),
            ],
            options={
                "verbose_name": "Колір",
                "verbose_name_plural": "Кольори",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(
                blank=True, to="catalog.productcolor", verbose_name="Кольори"
            ),
        ),
    ]
