# Generated by Django 4.2.7 on 2024-02-12 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_productcolor_product_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="discount",
            field=models.IntegerField(
                blank=True,
                help_text="Знижка у відсотках",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Знижка",
            ),
        ),
    ]
