# Generated by Django 4.2.7 on 2024-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_alter_productattribute_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWidth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Ширина продукта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ширина продукта",
                "verbose_name_plural": "Ширина продукта",
            },
        ),
        migrations.AddField(
            model_name="productattribute",
            name="custom_attribute",
            field=models.BooleanField(
                default=False,
                help_text="Позначати тільки якщо це кастомний варіант!",
                verbose_name="Кастомна варіація",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="max_len",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Максимальна довжина",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="min_len",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Мінімальна довжина",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="width",
            field=models.ManyToManyField(
                blank=True,
                related_name="widths",
                to="catalog.productwidth",
                verbose_name="Ширина",
            ),
        ),
    ]
