# Generated by Django 4.2.7 on 2024-02-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_productwidth_productattribute_custom_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="custom_price",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Позначати тільки якщо це кастомний варіант!",
                max_digits=5,
                verbose_name="Ціна за метр квадратний",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="max_len",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Позначати тільки якщо це кастомний варіант!",
                max_digits=4,
                null=True,
                verbose_name="Максимальна довжина",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="min_len",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Позначати тільки якщо це кастомний варіант!",
                max_digits=4,
                null=True,
                verbose_name="Мінімальна довжина",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="width",
            field=models.ManyToManyField(
                blank=True,
                help_text="Позначати тільки якщо це кастомний варіант!",
                related_name="widths",
                to="catalog.productwidth",
                verbose_name="Ширина",
            ),
        ),
    ]
