# Generated by Django 4.2.7 on 2024-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_productattribute_custom_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="custom_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Позначати тільки якщо це кастомний варіант!",
                max_digits=5,
                null=True,
                verbose_name="Ціна за метр квадратний",
            ),
        ),
    ]
