# Generated by Django 4.2.7 on 2024-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0024_alter_productattribute_custom_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated"
                    ),
                ),
                ("code", models.CharField(max_length=115, verbose_name="Код")),
                ("end_time", models.DateTimeField(verbose_name="Дата закінчення")),
            ],
            options={
                "verbose_name": ("Промокод",),
                "verbose_name_plural": "Промокоди",
            },
        ),
    ]
