# Generated by Django 4.2.7 on 2024-03-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0026_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="products/default.png",
                max_length=512,
                upload_to="products",
                verbose_name="Зображення",
            ),
        ),
    ]
