# Generated by Django 4.2.7 on 2024-03-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0027_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="is_new",
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=True, verbose_name="Новинка"),
        ),
    ]
