# Generated by Django 4.2.7 on 2024-04-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_productattribute_is_new_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
