# Generated by Django 4.2.7 on 2024-04-15 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_productreview_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.PositiveIntegerField(default=None, help_text='У відсотках', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Знижка'),
        ),
    ]
