# Generated by Django 4.2.7 on 2024-04-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_promocode_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоди'},
        ),
    ]
