# Generated by Django 4.2.7 on 2024-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_promocode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='main_sale',
            field=models.BooleanField(default=False, help_text='Позначати тільки якщо має відображатись на головній сторінці'),
        ),
    ]
