# Generated by Django 4.2.7 on 2026-01-17 15:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_product_active_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='texture',
            field=models.ImageField(blank=True, help_text='Альтернатива кольору. Якщо завантажено текстуру, вона буде відображатися замість кольору.', null=True, upload_to='colors/textures', verbose_name='Текстура'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Колір'),
        ),
    ]
