# Generated by Django 4.2.7 on 2026-01-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_add_texture_to_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationvalue',
            name='specification',
            field=models.ForeignKey(blank=True, help_text='Характеристика до якої належить це значення', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.specification', verbose_name='Характеристика'),
        ),
    ]
