# Generated by Django 4.2.7 on 2026-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_productattribute_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Короткий опис для сніпета (~150–160 символів). Пишіть як відповідь на інтент покупця, не keyword soup. Якщо порожньо — fallback з опису / бренду.', null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_keys',
            field=models.TextField(blank=True, help_text='Опційно. Google майже ігнорує; можна залишити порожнім.', null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_title',
            field=models.TextField(blank=True, help_text='Title у вкладці браузера / сніпеті. Якщо порожньо — використовується назва (title).', null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Короткий опис для сніпета (~150–160 символів). Пишіть як відповідь на інтент покупця, не keyword soup. Якщо порожньо — fallback з опису / бренду.', null=True, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keys',
            field=models.TextField(blank=True, help_text='Опційно. Google майже ігнорує; можна залишити порожнім.', null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.TextField(blank=True, help_text='Title у вкладці браузера / сніпеті. Якщо порожньо — використовується назва (title).', null=True, verbose_name='SEO Title'),
        ),
    ]
