# Generated by Django 4.2.7 on 2026-07-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_seo_meta_phase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Увімкнено за замовчуванням. Бейдж на сайті лише протягом N днів від дати створення (N у Налаштуваннях магазину, зараз 90). Зніми галочку, щоб сховати «Новинку» раніше.', verbose_name='Новинка'),
        ),
    ]
