# Generated by Django 6.0.7 on 2026-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_promocode_end_time_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-created',), 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Не показується на сайті. Потрібен, щоб звірити з замовленням.', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Опубліковано'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(default=False, help_text='Email збігся з виконаним замовленням на цей товар.', verbose_name='Перевірена покупка'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'status'], name='catalog_pro_product_37701e_idx'),
        ),
    ]
