# Generated by Django 4.2 on 2023-06-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product',
            new_name='product_attr',
        ),
    ]
