# Generated by Django 4.2.7 on 2024-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
