# Generated by Django 4.2.7 on 2024-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_cartproduct_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Тільки для кастомних варіацій",
                max_digits=6,
                null=True,
                verbose_name="Загальна ціна",
            ),
        ),
    ]
