# Generated by Django 4.2.7 on 2024-02-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0025_promocode"),
        ("cart", "0005_alter_cartproduct_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="catalog.promocode",
                verbose_name="Промокод",
            ),
        ),
    ]
