# Generated by Django 4.2.7 on 2025-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товар в корзині', 'verbose_name_plural': 'Товари в корзині'},
        ),
    ]
