# Generated by Django 4.2.7 on 2026-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Довжина кастомного товару в метрах', max_digits=5, null=True, verbose_name='Довжина'),
        ),
    ]
