# Generated by Django 6.0.7 on 2026-07-19 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='media_kind',
            field=models.CharField(choices=[('video', 'Video'), ('photos', 'Photo gallery')], db_index=True, default='video', help_text='video → Reels/FB/TT video; photos → IG/FB/TT photo carousel.', max_length=16),
        ),
        migrations.CreateModel(
            name='SocialPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('image', models.ImageField(upload_to='social/images/%Y/%m/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.socialpost')),
            ],
            options={
                'verbose_name': 'Social post image',
                'verbose_name_plural': 'Social post images',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
