# Generated by Django 6.0.7 on 2026-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_staff_comments_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsettings',
            name='staff_comments_enabled',
            field=models.BooleanField(default=True, help_text='Дублювати коментарі (TG discussion; пізніше IG/FB) у staff topic/чат.'),
        ),
    ]
