# Generated by Django 6.0.7 on 2026-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_socialsettings_staff_comments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsettings',
            name='auto_post_new_products_meta',
            field=models.BooleanField(default=False, help_text='Автоматично публікувати нові товари в Instagram/Facebook (photos-пост з головного фото + галереї).'),
        ),
    ]
