# Generated by Django 6.0.7 on 2026-07-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_socialsettings_auto_post_new_products_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsettings',
            name='auto_post_new_products_viber',
            field=models.BooleanField(default=False, help_text='Автоматично слати нові товари у Viber-канал (діє лише разом з увімкненим майстер-рубильником).'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='viber_posting_enabled',
            field=models.BooleanField(default=False, help_text='Майстер-рубильник Viber-каналу. Вимкнено = у Viber не постить НІЩО (ні авто, ні ручна дія в адмінці).'),
        ),
    ]
