# Generated by Django 6.0.7 on 2026-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialsettings_auto_post_new_products_viber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('platform', models.CharField(db_index=True, max_length=16)),
                ('external_comment_id', models.CharField(blank=True, default='', max_length=128)),
                ('tg_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('tg_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('comment_text', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=256)),
                ('post_url', models.URLField(blank=True, default='')),
                ('alert_chat_id', models.CharField(db_index=True, max_length=64)),
                ('alert_message_id', models.CharField(db_index=True, max_length=64)),
                ('raw_operator_text', models.TextField(blank=True)),
                ('draft_text', models.TextField(blank=True)),
                ('draft_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('drafted_by_tg_user', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('mirrored', 'Mirrored to staff'), ('awaiting_confirm', 'Awaiting confirm'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='mirrored', max_length=32)),
                ('sent_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Social comment reply',
                'verbose_name_plural': 'Social comment replies',
                'ordering': ('-created',),
            },
        ),
    ]
