# Generated by Django 6.0.7 on 2026-07-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_socialcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcommentreply',
            name='last_operator_message_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='socialcommentreply',
            name='status',
            field=models.CharField(choices=[('mirrored', 'Mirrored to staff'), ('awaiting_confirm', 'Awaiting confirm'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='mirrored', max_length=32),
        ),
    ]
