# Generated by Django 6.0.7 on 2026-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_socialcommentreply_last_operator_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('open_id', models.CharField(blank=True, default='', max_length=128)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('client_key', models.CharField(blank=True, default='', help_text="client_key the tokens were issued for (sandbox keys start with 'sb').", max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('refresh_fail_count', models.PositiveIntegerField(default=0)),
                ('reauth_warned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TikTok token',
                'verbose_name_plural': 'TikTok token',
            },
        ),
    ]
