# Generated by Django 6.0.7 on 2026-07-20 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_promocode_end_time_optional'),
        ('social', '0009_tiktoktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokDailyPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('picked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('generated', 'Відео згенеровано'), ('published', 'Опубліковано'), ('failed', 'Помилка')], default='generated', max_length=16)),
                ('video_path', models.CharField(blank=True, default='', help_text='Згенерований MP4; чиститься після PUBLISH_COMPLETE.', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(blank=True, help_text='Порожньо = товар видалили після піку (історія лишається).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_picks', to='catalog.product')),
                ('social_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_picks', to='social.socialpost')),
            ],
            options={
                'verbose_name': 'TikTok daily pick',
                'verbose_name_plural': 'TikTok daily picks',
                'ordering': ('-picked_at', '-id'),
                'indexes': [models.Index(fields=['cycle_number', 'status'], name='social_tikt_cycle_n_b59fd3_idx'), models.Index(fields=['-picked_at'], name='social_tikt_picked__223528_idx')],
            },
        ),
    ]
