# Generated by Django 6.0.7 on 2026-07-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_promocode_end_time_optional'),
        ('social', '0010_tiktokdailypick'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsettings',
            name='tiktok_auto_enabled',
            field=models.BooleanField(default=False, help_text='Майстер-рубильник щоденної авто-генерації відео для TikTok.'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='tiktok_monthly_budget_usd',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Жорстка стеля витрат на генерацію за календарний місяць. Рахуються ВСІ прогони, включно з невдалими.', max_digits=7),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='tiktok_vertical_image_model',
            field=models.CharField(blank=True, default='openai/gpt-image-2', help_text='Модель, що перекадровує 4:3 фото в 9:16 (та сама, що для фото товарів).', max_length=128),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='tiktok_video_draft',
            field=models.BooleanField(default=False, help_text='Draft-режим: у 4 рази дешевше, але візерунок килима «пливе». Тільки для тестів, не для бойових постів.'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='tiktok_video_model',
            field=models.CharField(blank=True, default='prunaai/p-video', help_text='Модель i2v. Пропорції беруться з вхідного фото, не з параметра.', max_length=128),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='tiktok_video_resolution',
            field=models.CharField(blank=True, default='720p', help_text='720p ($0.02/с) або 1080p ($0.04/с — пробиває стелю $5/міс).', max_length=8),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='tiktok_video_seconds',
            field=models.PositiveSmallIntegerField(default=6, help_text='Тривалість відео. Ціна лінійна: $0.02/с на 720p.'),
        ),
        migrations.CreateModel(
            name='TikTokVerticalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('image', models.ImageField(upload_to='social/tiktok/vertical')),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_vertical_image', to='catalog.product')),
                ('source_image', models.ForeignKey(blank=True, help_text='Вихідне is_ai фото, з якого зроблено вертикаль.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productimage')),
            ],
            options={
                'verbose_name': 'TikTok vertical image',
                'verbose_name_plural': 'TikTok vertical images',
            },
        ),
        migrations.CreateModel(
            name='TikTokGenerationSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('kind', models.CharField(choices=[('image', 'Вертикальне фото 9:16'), ('video', 'Відео')], max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('succeeded', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spends', to='social.tiktokdailypick')),
            ],
            options={
                'verbose_name': 'TikTok generation spend',
                'verbose_name_plural': 'TikTok generation spend',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['-created'], name='social_tikt_created_3d8f18_idx')],
            },
        ),
    ]
