# Generated by Django 6.0.7 on 2026-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_socialsettings_tiktok_auto_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsettings',
            name='tiktok_audit_passed',
            field=models.BooleanField(default=False, help_text='⚠️ ЗНІМАЄ ЗАХИСТ. Поки вимкнено — усі пости йдуть SELF_ONLY (видно лише власнику). Увімкнення дозволяє ПУБЛІЧНІ пости й має сенс ЛИШЕ після реального схвалення TikTok audit. Це НЕ вмикач автопостингу — для нього є «Авто-генерація TikTok» нижче.'),
        ),
    ]
