# Generated by Django 6.0.7 on 2026-07-20 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_socialsettings_tiktok_audit_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokdailypick',
            name='montage_path',
            field=models.CharField(blank=True, default='', help_text='Готовий монтаж, який тягнуть площадки; чиститься проходом по віку.', max_length=500),
        ),
        migrations.AlterField(
            model_name='tiktokdailypick',
            name='status',
            field=models.CharField(choices=[('generated', 'Відео згенеровано'), ('published', 'Опубліковано'), ('partial', 'Опубліковано частково'), ('failed', 'Помилка')], default='generated', max_length=16),
        ),
        migrations.AlterField(
            model_name='tiktokdailypick',
            name='video_path',
            field=models.CharField(blank=True, default='', help_text='Сирий кліп з моделі; чиститься проходом по віку.', max_length=500),
        ),
        migrations.CreateModel(
            name='VideoDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram Reels'), ('facebook', 'Facebook'), ('threads', 'Threads'), ('youtube', 'YouTube Shorts')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('publishing', 'Публікується'), ('published', 'Опубліковано'), ('published_private', 'Опубліковано приватно'), ('failed', 'Помилка'), ('skipped', 'Пропущено')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=190)),
                ('external_url', models.URLField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='social.tiktokdailypick')),
            ],
            options={
                'verbose_name': 'Video delivery',
                'verbose_name_plural': 'Video deliveries',
                'ordering': ('pick_id', 'platform'),
                'indexes': [models.Index(fields=['status', 'platform'], name='social_vide_status_edbc5b_idx')],
                'unique_together': {('pick', 'platform')},
            },
        ),
    ]
