# Generated by Django 6.0.7 on 2026-07-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_tiktokdailypick_montage_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsettings',
            name='video_comments_thread_id',
            field=models.CharField(blank=True, default='', help_text='Окремий forum-топік для відео-мереж (TikTok/Reels/Threads/Shorts): звіти щоденного ролика і коментарі під ним. Порожньо = все падає у звичайний топік коментарів.', max_length=32, verbose_name='Video topic (thread_id)'),
        ),
    ]
