# Generated by Django 6.0.7 on 2026-07-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_socialsettings_video_comments_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsettings',
            name='video_facebook_enabled',
            field=models.BooleanField(default=False, help_text='Постити щоденний ролик на сторінку. Потребує META_PAGE_ID.', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='video_instagram_enabled',
            field=models.BooleanField(default=False, help_text='Постити щоденний ролик у Reels. Потребує META_IG_USER_ID.', verbose_name='Instagram Reels'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='video_threads_enabled',
            field=models.BooleanField(default=False, help_text='Потребує окремого Threads-токена (не Meta page token).', verbose_name='Threads'),
        ),
        migrations.AddField(
            model_name='socialsettings',
            name='video_youtube_enabled',
            field=models.BooleanField(default=False, help_text='Не вмикати до проходження YouTube compliance audit: без нього API мовчки робить відео приватним, і публічним його вже не зробити ніколи.', verbose_name='YouTube Shorts'),
        ),
    ]
