# Generated by Django 6.0.7 on 2026-07-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_socialsettings_video_facebook_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodelivery',
            name='post_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Ідентифікатор поста, коли він відрізняється від external_id (Facebook).', max_length=190),
        ),
    ]
