# Generated by Django 6.0.7 on 2026-07-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_videodelivery_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('username', models.CharField(blank=True, default='', max_length=190)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('refresh_fail_count', models.PositiveIntegerField(default=0)),
                ('reauth_warned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threads token',
                'verbose_name_plural': 'Threads token',
            },
        ),
    ]
