# Generated by Django 6.0.7 on 2026-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_video_topic_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('channel_id', models.CharField(blank=True, default='', max_length=128)),
                ('channel_title', models.CharField(blank=True, default='', max_length=190)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('refresh_fail_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube token',
                'verbose_name_plural': 'YouTube token',
            },
        ),
    ]
