# Generated by Django 6.0.7 on 2026-07-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_youtubetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('collected_on', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('age_hours', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='social.videodelivery')),
            ],
            options={
                'verbose_name': 'Video metric',
                'verbose_name_plural': 'Video metrics',
                'ordering': ('-collected_on', 'delivery_id'),
                'unique_together': {('delivery', 'collected_on')},
            },
        ),
    ]
