# Generated by Django 4.2.7 on 2024-01-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Замовлення", "verbose_name_plural": "Замовлення"},
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Адреса"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.CharField(default=1, max_length=512, verbose_name="Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Повідомлення"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                default=1, max_length=128, verbose_name="Спосіб оплати"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="surname",
            field=models.CharField(default=1, max_length=512, verbose_name="Прізвище"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(blank=True, null=True, verbose_name="Total price"),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=512, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Телефон"
            ),
        ),
    ]
