# Generated by Django 4.2.7 on 2024-02-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_options_order_address_order_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Номер замовлення"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("КОМПЛЕКТУЄТЬСЯ", "Комплектується"),
                    ("ВІДПРАВЛЕНО", "Відправлено"),
                    ("ВИКОНАНО", "Виконано"),
                    ("СКАСОВАНО", "Скасовано"),
                ],
                default="КОМПЛЕКТУЄТЬСЯ",
                max_length=155,
                verbose_name="Статус замовлення",
            ),
        ),
    ]
