# Generated by Django 4.2.7 on 2024-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_order_number_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="Номер замовлення"
            ),
        ),
    ]
