# Generated by Django 4.2.7 on 2024-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.BigIntegerField(
                blank=True, editable=False, null=True, verbose_name="Номер замовлення"
            ),
        ),
    ]
