# Generated by Django 4.2.7 on 2024-04-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_promocode_options'),
        ('order', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.promocode', verbose_name='Промокод'),
        ),
    ]
