# Generated by Django 4.2.7 on 2024-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Комплектується', 'Комплектується'), ('Відправлено', 'Відправлено'), ('Виконано', 'Виконано'), ('Скасовано', 'Скасовано'), ('Не оплачено', 'Не оплачено')], default='Комплектується', max_length=155, verbose_name='Статус замовлення'),
        ),
    ]
