# Generated by Django 4.2.7 on 2025-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Комплектується, оплачено', 'Комплектується, оплачено'), ('Відправлено', 'Відправлено'), ('Виконано', 'Виконано'), ('Скасовано', 'Скасовано'), ('Не оплачено', 'Не оплачено')], default='Комплектується, оплачено', max_length=155, verbose_name='Статус замовлення'),
        ),
    ]
