# Generated by Django 4.2.7 on 2026-07-17 22:39

from django.db import migrations, models


STATUS_MAP = {
    "Комплектується, оплачено": "paid",
    "Відправлено": "shipped",
    "Виконано": "completed",
    "Скасовано": "cancelled",
    "Не оплачено": "awaiting_payment",
    # already-new codes stay as-is
    "new": "new",
    "awaiting_payment": "awaiting_payment",
    "paid": "paid",
    "shipped": "shipped",
    "completed": "completed",
    "cancelled": "cancelled",
}


def migrate_order_data(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    for order in Order.objects.all().iterator():
        updates = []

        mapped = STATUS_MAP.get(order.status)
        if mapped:
            new_status = mapped
        else:
            new_status = "new"

        # cash COD wrongly defaulted to "paid/assembling" → fix to "new"
        if order.payment_type == "cash" and new_status == "paid":
            new_status = "new"

        if new_status != order.status:
            order.status = new_status
            updates.append("status")

        if not getattr(order, "city", None) and order.address:
            city = str(order.address).split(",", 1)[0].strip()
            if city:
                order.city = city[:255]
                updates.append("city")

        if updates:
            order.save(update_fields=updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created",),
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="Місто",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="Номер замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "Оплата при отриманні"),
                    ("liqpay", "Онлайн оплата (LiqPay)"),
                ],
                max_length=128,
                verbose_name="Спосіб оплати",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(
                blank=True, db_index=True, null=True, verbose_name="Сума"
            ),
        ),
        # Convert old Ukrainian status labels → codes while column is still wide
        migrations.RunPython(migrate_order_data, noop_reverse),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Нове"),
                    ("awaiting_payment", "Очікує оплати"),
                    ("paid", "Оплачено, комплектується"),
                    ("shipped", "Відправлено"),
                    ("completed", "Виконано"),
                    ("cancelled", "Скасовано"),
                ],
                db_index=True,
                default="new",
                max_length=32,
                verbose_name="Статус замовлення",
            ),
        ),
    ]
