# Generated by Django 6.0.7 on 2026-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_ga4_mp_sent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promocoderedemption',
            new_name='order_promo_promoco_86f082_idx',
            old_name='order_promo_promoco_idx',
        ),
        migrations.AlterField(
            model_name='promocoderedemption',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='promocoderedemption',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
    ]
