# Generated by Django 6.0.7 on 2026-07-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_order_promo_promoco_idx_order_promo_promoco_86f082_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ga4_client_id',
            field=models.CharField(blank=True, default='', editable=False, help_text="Значення з куки _ga на момент оформлення. Потрібне, щоб покупка прив'язалась до сесії, з якої людина прийшла.", max_length=64, verbose_name='GA4 client_id'),
        ),
    ]
