# Generated by Django 6.0.7 on 2026-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_ga4_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_request_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Порожньо = ще не просили. Один лист на замовлення, не більше.', null=True, verbose_name='Прохання про відгук надіслано'),
        ),
    ]
