# Generated by Django 6.0.7 on 2026-07-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_review_request_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Момент переходу в статус «Виконано». Окреме поле, бо `updated` зсувається від будь-якої правки замовлення.', null=True, verbose_name='Стало «Виконано»'),
        ),
    ]
